### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by juliardi** [DoubleLabyrinth/how-does-navicat-encrypt-password#3]
I want to use my Java implementation based on your Python and VB.NET implementation (I've send the pull request at #2, please review them), but I am not sure if it's allowed considering that you are not listing any License statement in this repository. 
So, would you consider adding a license to this repository?
Thank you

**Comment by DoubleLabyrinth** [comment]
Oh, I'm sorry that I forgot your pull request. Well, I hardly use Java. It has been several years since I fixed some bugs of a game server last time. So when I saw your pull request a few weeks ago, I decided to check your code later. But, you see, I forgot. I'm sorry. I will check it as quickly as possible.

As for license, well, I have never think of that. Because, you see, few of people star it or fork it. This repository is not a formal project. I wrote it just for telling people what I found. Now you talk about it. I say this repository uses General Public License.

**Comment by juliardi** [comment]
Thank you for your response. I am sure that you have a good will, considering that you share this in a public repository. 
Just a suggestion here, that having an explicit `LICENSE` file in your repository will be more reassuring, and someone like me won't need to ask for your permission explicitly each time they want to use your code.

**Comment by juliardi** [comment]
According to
https://www.apache.org/licenses/GPL-compatibility.html
and 
https://github.com/rubychan/coderay/issues/25
it looks like a GPL licensed code can't be used in Apache 2.0 licensed software (it is a one-way compatibility). 
So, would you mind to change this repository license to a more permissive license such as Apache 2.0 or MIT license? By using them, I think your work would be more open to the public :)

**Comment by DoubleLabyrinth** [comment]
Ok, I have set it MIT license.

**Comment by juliardi** [comment]
Wow, thank you for accepting my request :)
